# Generated by Django 2.2.5 on 2021-04-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_choose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], max_length=20)),
                ('merchant_invoice_id', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.FloatField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Charge')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Merchant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Unit'),
        ),
        migrations.AddField(
            model_name='charge',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='courier.Zone'),
        ),
    ]
