# Generated by Django 2.2.5 on 2021-04-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='charge',
        ),
        migrations.AddField(
            model_name='parcel',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courier.Unit'),
            preserve_default=False,
        ),
    ]
